### ISSUE TITLE
KeyError: 'DX'

### ISSUE THREAD

**Issue by 25th-engineer** [voidstrike/ASGIT#1]
KeyError: 'DX'.
I tried to run the pix2pix_attn model but failed due to the  above error.

**Comment by voidstrike** [comment]
@25thengineer Hey, it looks like you are running a supervised translation task. Could you please provide the dataset and the command you tried?

**Comment by 25th-engineer** [comment]
Thanks for reply and so sorry for delay.
Now I had a new error that the error details are shown below and yes I'm trying to run a supervised translation task based on your model **pix2pix_attn**.
Error information:
```
Traceback (most recent call last):
  File "train_attn.py", line 100, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "/mnt/ASGIT_main/models/pix2pix_attn_model.py", line 130, in optimize_parameters
    self.forward()                   # compute fake images: G(A)
  File "/mnt/ASGIT_main/models/pix2pix_attn_model.py", line 101, in forward
    self.fake_B = self.netG(self.real_A * (1. + concat_attn_A))
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'y_t' and 'r_t'
```

Here are my dataset structure:
```
1098
├── test
├── testA
├── testB
├── train
├── trainA
├── trainB
├── val
├── valA
├── valB
└── readme.txt
```
I uploaded the dataset to the [Google Drive](https://drive.google.com/file/d/1XGxLJgbUBUtWcUPJ5FWLuh7LlGJUY0TD/view?usp=sharing)

<br>
And the command I used:

```
python train_attn.py --dataroot /mnt/data/pix2pix_dataset_bubble/1098/ --model pix2pix_attn --netD trainable_attn --netG resnet_9blocks_4
```

Thanks for your share and help in advance.

**Comment by voidstrike** [comment]
Yeah, I got it. Sorry for the confusion caused by the code, I didn't well clean the code for supervised translation.
Please refer to the following points:

- Supervised translation requires a paired dataset and that's the reason I'm asking for the dataset. Since the code is inherited from the CycleGAN repo, you need to manually create the dataset with the same format. (e.g. img_A has size 512 * 512  and img_B has size 512 * 512, you need to combine them into a 512 * 1024 image, please refer to `src/dataset/combine_A_and_B.py` for some hints)
- `resnet_9blocks_X` (1, 2, 3, 4) are used for ablation study and requires additional parameters to run, please just use `resnet_9blocks` or `resnet_6blocks`
- You should set `--mask_size` to the size of your image (default is 256)

**Comment by 25thengineer** [comment]
Thanks again. :+1: 
It seems I had the another error and I gave up trying to run the repo.
![image](https://user-images.githubusercontent.com/15064573/114032846-49d00380-98af-11eb-9ca8-72c255a0233d.png)

**Comment by 25th-engineer** [comment]
Thanks again. :+1: 
It seems I had the another error and I gave up trying to run the repo.
![image](https://user-images.githubusercontent.com/15064573/114032846-49d00380-98af-11eb-9ca8-72c255a0233d.png)
